# ~/.bash_profile
#
# This is executed by bash when starting a login shell, interactive or not.
#

source ~/.bash.d/helpers

sourcePartsInFile "$BASHD_GEN"
sourcePartsInFile "$BASHD_LOG"

[[ isInteractive ]] && sourcePartsInFile "$BASHD_INT"

# The End.


PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
