# ~/.bash_profile
#
# This is executed by bash when starting a login shell, interactive or not.
#

source ~/.bash.d/helpers

sourceFilesInDir "$BASHD_ALL"
sourceFilesInDir "$BASHD_LOG"

[[ isInteractive ]] && sourceFilesInDir "$BASHD_INT"

# The End.

