# ~/.bash_profile
#
# This is executed by bash when starting a login shell, interactive or not.
#

source ~/.bash.d/helpers

sourcePartsInDir "$BASHD_GEN_D"
sourcePartsInDir "$BASHD_LOG_D"

[[ isInteractive ]] && sourcePartsInDir "$BASHD_INT_D"

# The End.

